server {
    listen 80;
    server_name localhost;

    # 빌드된 정적 파일들이 위치하는 경로
    root /usr/share/nginx/html;
    
    # 기본 인덱스 파일 지정
    index index.html;

    # 최상위 경로 설정 (React SPA 라우팅 호완성)
    location / {
        # 1. 파일이 있으면 서빙
        # 2. 폴더가 있으면 서빙
        # 3. 모두 실패하면 index.html 로 넘겨서 React Router 가 처리하게 함
        try_files $uri $uri/ /index.html;
    }
}
